apiVersion: v1
kind: Secret
metadata:
  name: ntfy-auth
type: Opaque
data:
  NTFY_AUTH_USERS: ENC[AES256_GCM,data:rajm4IHHmDqUZ8NNm59ZONm2QPWrRMPG2qE5qqNknH2ubRhEskq3xh18oaXOBNoZEwPQFRoVNqdsYybQw8xB8+wqskizcKBojs7jAyUo1ZpRS3JhBwAPWqelsl3aYhYY8p3wC3aCrFBmNBXRrEeyStAi1518THtO/tzyDNfxClGGfucYsG4s62nulI/0wvNLrJpX9/MYaymkxYUykej92YBA2eZVf13NIX1J5TW1wULnlmUXpEDTP/FtX1EldqN+LhOQ6fUM6qhHcrEBQg7ZDmvCXjLXkszXC5cNT8bbYdOJxojYz624kXWhncXUiz8r+6JQ28HGYdLALSDRz+xXs3rUS7SkUnxgkPUU64SD8xms9AwbmbGVTEfu0ulfkl0Plg8vAXTY1CY=,iv:mJda6b2wVEXnOgcb45Xua8YDx4jgjTrY5w88UfuHNd0=,tag:WTuj8JUxP+9Y5EhKBgyhvg==,type:str]
  NTFY_AUTH_TOKENS: ENC[AES256_GCM,data:v6X6n3acRgJ51WApfFCxT719eWlWcvqsQNZny54eYE66c1igDRR1lT1Zk1ZDX3u9SpZabzEzoLt6O48Pzqy6MWe5pbuhjM2f5gORZFY1bOIHWwKJgr+LeuZP7OT/vPhY/GoJmzHigjsunJ9MCBX2+vIpvEwbl5okkl9RNxASrPXkDAPMM52kkhx50GGIK8Oy,iv:VSstESeFapBooAcniyBY9gl/xLxYCIA3Y6R4nSq4/h0=,tag:GyHr+ysf2Ny00ScIL8RXYQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4d2J1QW5CczZMWXFmdmVK
        T2sxMXVZSG8xb0M2TFgxdDBvd3gwRTJNQUdNCktlQ3VXdEhJUXE4dHM3WmdqWS9z
        aG9mYTRMTFZqd0xhZG5wWUVjd0pyV1UKLS0tIGRWcFBoalRWTmRLRTFsWXNBNnNK
        WnRNTlJhUGtQaXY4dGxyaWl2bWljVncKcUzTZITWLMrxnPJK7sTAnEmh32/fjiP4
        hTYbXjh2dIybWrd/x108ntv7Xs1P2O6Pa5zx1wWEv3rzz+d/fX0Jlg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-03T16:03:20Z"
  mac: ENC[AES256_GCM,data:oniBFKnepde5EDYeB570hTebFCzCxcIxtsUpKL3NEi2JFObolJ8fo1uQ2OjAYzzt5Sk2pHiM6B+RcZT1D6QRgbvE4mbMw4Wq8XZzGsfRjAa3M/PrefgJvHJ/6ol8g4/VcL2B4DFi0dDfaPIpNWmlR0CloTtgMjbUjc96uRspc0g=,iv:BIqXACLp05LQuXtLDUWXRGnjyVPvaGO5Xzb7DwBPcJI=,tag:zor7cgB85KhJZRJC3jywBw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
