apiVersion: v1
kind: Secret
metadata:
  name: cli-proxy-api-secret
type: Opaque
stringData:
  config.yaml: ENC[AES256_GCM,data:GqeEMhs+tYc5zn7Q/e9sAWMXIWjcqYpPKalARk+pZ5Jk5gpTWED8VLh8dfNrM2mO2q3PDOVi6qrpLkYSzZyShnncGzvMDt8To1BPcTqBJBvsBLMuAiY9l54Lxts6kbK8wVfWsyegmMFXGPNvGFoNMWNzw05kQ1pJ5gWsU6oC1Ty0XzNIho48bI3JA1z0L0E01WS2jAOy/oSv0K8EvWIWaGa1MjL74DUCUbdJHaUuz8cCyL3FDM2ViUqsecV38XYwSaS+SJKOW87O6rdTw0mgLOXbPdyWKrStJ7xGZ3Qs9+YFFmvKlU8bV1nw3aemc+s7bB5Q9x1B1Ij0r7nqbQXIGD52awXp34dqrHOf1YzerPGjxEx5EBjaPMI8iwckrCxuAj8wcyTVEqT/SjABeV6LjYflI/V+tCR+xGV8QrJACFghZD0=,iv:+13sir+5jSHDRMsN+NsJeUfbWxvPX1iXH/BtvD4acSk=,tag:oRo7N+/VVvqY2sVafAWmqQ==,type:str]
  management-password: ENC[AES256_GCM,data:3nr5uC/+5NSuZb82g4pyH2UJylIMleGP1WRZ7gwiSfL4jMJnXxnV/J5dGQ==,iv:f/E7L+jRPnAZ7+E0tOHT4Ott7yt3LnBZ0gZ+OZ7II5o=,tag:/FOszzhCWF8C2KSZ3pFvUw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDRTZpUGROT043bWNkcTJ2
        ckp6aUFRRURQeXhqVmlobVFmYkp2K3UrMVZnCm9TNlhPTGV6a2hab2ZaVk5Qcll2
        ZlVBdVhnejBPcHpaV0xMVFNueHNmYVEKLS0tIG1yNE9IaUN6R1BQeDNWenNVZE1s
        UFhzZ3lHMENDbHMxOU05YitRRWpQV3MKE7Kus4h6Ib2pEYRsaPGk74Oaj7yeu3+6
        ermEBYFeV0p3K9BUpw9gU6RuZyJMmd4YsBSNRD4swCcffJvN+ZLtRw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-29T09:22:06Z"
  mac: ENC[AES256_GCM,data:HigUyOrP0oBo2mCzb+6PlNF0oPwrjoq3VcwucykI00fDGnbm5/brNkeL7fT+6zTA3QlHIIe6Wn4/aFBaJoV/WaKyo9MZyvLbLZIiTkRqYiiWOQD1ud31Ekigc6YvL/7cv4HN7AiINliBdEEn62hS7iFt8WBVahCTauYBk9L0bfo=,iv:pMY0KeMqRFUK1qeXi0Pi5Ti46ujsNPUbYJ8poOVgtNU=,tag:XDu1+SnqjEN+hWWC5tImtg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
